### ISSUE TITLE
SuggestionsConfig.TextConfig

### ISSUE THREAD

**Issue by Faridka0** [huemae/SuggestionsKit#2]
Text color doesn't change

**Comment by AlphanumericCharactersOrSingleHyphenz** [comment]
> Text color doesn't change 

Thanks. Will fix it as soon as possible(today)

**Comment by AlphanumericCharactersOrSingleHyphenz** [comment]
> Text color doesn't change

fixed in 1.2.6

**Comment by Faridka0** [comment]
Thank you for your quick response and solution!
